Sir Kindly check and approve RP
mrehanabbasi/appraisal-system-backend pull request #4
Opened 2023-02-19 16:44 UTC by hamziHashmi

2023-02-21 05:23 UTC, mrehanabbasi requested changes
I haven't tested the GET, PUT and DELETE methods as the POST method itself is giving error. Please fix as per the comments and DO NOT CREATE A NEW PULL REQUEST. The changes should be highlighted in the same PR.

2023-02-21 05:23 UTC, mrehanabbasi commented on models/models.go
> +type Role struct {
What will be their JSON names in the request and response? Also, not all names for DB/GORM are provided.

2023-02-21 05:23 UTC, mrehanabbasi commented on controller/controller.go
> +		c.AbortWithStatus(http.StatusInternalServerError)
Abort is mostly used with middlewares. Use `c.JSON()` instead. Also, add a message in the response to show the user what the error is.

2023-02-21 05:23 UTC, mrehanabbasi commented on controller/controller.go
> +		c.AbortWithStatus(http.StatusBadRequest)
Abort is mostly used with middlewares. Use `c.JSON()` instead. Also, add a message in the response to show the user what the error is.

2023-02-21 05:23 UTC, mrehanabbasi commented on controller/controller.go
> +		c.AbortWithStatus(http.StatusNotFound)
Abort is mostly used with middlewares. Use `c.JSON()` instead. Also, add a message in the response to show the user what the error is.

2023-02-21 05:23 UTC, mrehanabbasi commented on controller/controller.go
> +		c.AbortWithStatus(http.StatusBadRequest)
Abort is mostly used with middlewares. Use `c.JSON()` instead. Also, add a message in the response to show the user what the error is.

2023-02-21 05:23 UTC, mrehanabbasi commented on controller/controller.go
> +		c.AbortWithStatus(http.StatusInternalServerError)
Abort is mostly used with middlewares. Use `c.JSON()` instead. Also, add a message in the response to show the user what the error is.

2023-02-21 05:23 UTC, mrehanabbasi commented on controller/controller.go
> +		c.AbortWithStatus(http.StatusInternalServerError)
Abort is mostly used with middlewares. Use `c.JSON()` instead. Also, add a message in the response to show the user what the error is.

2023-02-21 05:23 UTC, mrehanabbasi commented on controller/controller.go
> +		c.AbortWithStatus(http.StatusNotFound)
Abort is mostly used with middlewares. Use `c.JSON()` instead. Also, add a message in the response to show the user what the error is.

2023-02-21 05:23 UTC, mrehanabbasi commented on controller/controller.go
> +		c.AbortWithStatus(http.StatusInternalServerError)
Abort is mostly used with middlewares. Use `c.JSON()` instead. Also, add a message in the response to show the user what the error is.

2023-02-21 05:23 UTC, mrehanabbasi commented on controller/controller.go
> +	if err := r.db.Create(&role).Error; err != nil {
Where is the code to create a table? This will give error that `Table:<dbName>.roles doesn't exist.`

2023-02-22 12:48 UTC, mrehanabbasi requested changes

2023-02-22 12:48 UTC, mrehanabbasi commented on controller/roles.go
> +	c.JSON(http.StatusOK, role)
Complete role object might not be sent as response.

2023-02-22 12:48 UTC, mrehanabbasi commented on controller/roles.go
> +	return nil
Return both role and error.

2023-02-22 12:48 UTC, mrehanabbasi commented on controller/roles.go
> +	c.JSON(http.StatusOK, role)
Updated role might not be sent as response.

2023-02-22 12:48 UTC, mrehanabbasi commented on controller/roles.go
> +	return db.RowsAffected, nil
Why are `RowsAffected` being returned when it is not being used?

2023-02-22 12:48 UTC, mrehanabbasi commented on routes/router.go
> +			roles.GET("", roleController.GetAllRoles)
Instead of just empty route, use "/" instead. That is a good practice.

2023-02-22 12:48 UTC, mrehanabbasi commented on routes/router.go
> +			roles.POST("", roleController.CreateRole)
Instead of just empty route, use "/" instead. That is a good practice.

2023-03-01 07:03 UTC, mrehanabbasi requested changes
Greate work. Just these few small changes are required.

2023-03-01 07:03 UTC, mrehanabbasi commented on database/db.go
> +func Connect() *gorm.DB {
You do not need to return anything from this function.

2023-03-01 07:03 UTC, mrehanabbasi commented on database/db.go
> +	return DB
No return required.

2023-03-01 07:03 UTC, mrehanabbasi commented on controller/roles.go
> +	if roleName != "management" && roleName != "supervisor" && roleName != "hr" && roleName != "employee" {
As already discussed earlier, we need to check the database for existing role names. What if another role (e.g. "Mentor") is to be added? This will result in an error with this statement.

2023-03-01 07:03 UTC, mrehanabbasi commented on controller/roles.go
> +	roleName := strings.ToLower(string(role.RoleName))
As already discussed earlier, we need to check the database for existing role names. What if another role (e.g. "Mentor") is to be added? This will result in an error with this statement.

2023-03-01 07:05 UTC, mrehanabbasi commented
Also, add the table name in the database queries.

2023-03-01 07:24 UTC, mrehanabbasi requested changes

2023-03-01 07:24 UTC, mrehanabbasi commented on controller/roles.go
> +	c.JSON(http.StatusOK, gin.H{"message": "Role deleted successfully"})
Instead of sending a message for deletion, just send the status code of 204 i.e. No Content.
```go
c.Status(http.StatusNoContent)
```

2023-03-02 14:27 UTC, mrehanabbasi requested changes

2023-03-02 16:37 UTC, hamziHashmi commented
Changes are done Sir

2023-03-07 04:57 UTC, mrehanabbasi requested changes

2023-03-07 04:57 UTC, mrehanabbasi commented on controller/roles.go
> +	if err := db.Table("roles").Create(&role).Error; err != nil {
Before creating a role, it should check if that role name already exists in the database.

2023-03-07 04:57 UTC, mrehanabbasi commented on controller/roles.go
> +	err := db.Table("roles").Updates(role).Error
Before updating a role, it should check if the new role name already exists in the database.

2023-03-07 04:57 UTC, mrehanabbasi commented on controller/roles.go
> +func DeleteRole(db *gorm.DB, role *models.Role, id int) error {
A better approach will be:
```go
func DeleteRole(db *gorm.DB, role *models.Role, id int) error {
  err := db.Table("roles").Where("id = ?", id).Delete(&role).Error
  if err != nil {
    return err
  }
  return nil
}
```

2023-03-07 04:57 UTC, mrehanabbasi commented on controller/roles.go
> +		err = r.Db.Where("role_name = ? AND is_active = ?", roleName, isActive).Find(&role).Error
Use `Db.Table()` before `Where()`.

2023-03-07 04:57 UTC, mrehanabbasi commented on controller/roles.go
> +		err = r.Db.Where("role_name = ?", roleName).Find(&role).Error
Use `Db.Table()` before `Where()`.

2023-03-07 04:57 UTC, mrehanabbasi commented on controller/roles.go
> +		err = r.Db.Where("is_active = ?", isActive).Find(&role).Error
Use `Db.Table()` before `Where()`.

2023-03-07 05:10 UTC, mrehanabbasi commented on models/roles.go
> +	RoleName string `gorm:"size:100; not null;unique" json:"role_name"`
Remove spaces inside the gorm tag:
```go
RoleName string `gorm:"size:100;not null;unique" json:"role_name"`
```

2023-03-07 05:32 UTC, hamziHashmi commented
Sir, I have made the changes, please take a look at them.

2023-03-07 06:03 UTC, mrehanabbasi approved these changes

2023-03-07 07:20 UTC, merged