Sir review my code and accept PR
mrehanabbasi/appraisal-system-backend pull request #5
Opened 2023-02-20 04:55 UTC by Shery535

2023-02-21 06:12 UTC, mrehanabbasi requested changes
Great work. Please look at the comments and resolve in this same PR.

2023-02-21 06:54 UTC, Shery535 commented
ok Sir I understand it and i will modified the code according to your
instructions

2023-02-21 10:13 UTC, mrehanabbasi commented
Fogot to add one more comment: Replace all instances of `User` with `Employee` to be consistent with requirements.

2023-02-21 10:22 UTC, mrehanabbasi requested changes

2023-02-21 10:22 UTC, mrehanabbasi commented on controller/empl_controller.go
> +func (uc *UserController) CreateUser(c *gin.Context) {
The default role assigned to the an employee on its creation should be "Employee".

2023-02-21 10:22 UTC, mrehanabbasi commented on models/employee.go
> +type Employee struct {
Use `omitempty` in JSON for all those values which might not be present in the response.

2023-02-21 10:22 UTC, mrehanabbasi commented on routes/router.go
> +	r := gin.Default()
Do not change the variable name as it will cause conflict with others.

2023-02-21 12:45 UTC, mrehanabbasi requested changes

2023-02-21 12:45 UTC, mrehanabbasi commented on controller/empl_controller.go
> +func New() *EmployeeController {
Replace `New()` with `NewEmployeeController()` or somthing similar so that it does not cause conflict with others.

2023-02-21 12:45 UTC, mrehanabbasi commented on controller/empl_controller.go
> +	err = db.Preload("Role").Preload("Supervisor").Find(&Employee).Error
You only need to look in the employees table to find the employees. Also, there will be no supervisor table. Supervisor will also be an employee with the role "Supervisor".

2023-02-21 12:45 UTC, mrehanabbasi commented on controller/empl_controller.go
> +	err = db.Preload("Role").Preload("Supervisor").Where("id = ?", id).First(&Employee).Error
You only need to look in the employees table to find the employees. Also, there will be no supervisor table. Supervisor will also be an employee with the role "Supervisor".

2023-02-21 12:45 UTC, mrehanabbasi commented on controller/empl_controller.go
> +	err = db.Preload("Role").Preload("Supervisor").Where("name = ?", name).Statement.Find(&Employee).Error
You only need to look in the employees table to find the employees. Also, there will be no supervisor table. Supervisor will also be an employee with the role "Supervisor".

2023-02-21 12:45 UTC, mrehanabbasi commented on routes/router.go
> +	v1.GET("/employee/:name", uc.GetEmployeeByName)
Query parameter for name will be like this in the URL:
```
http://localhost:8080/v1/employees?name=name1
```
This will be part of the `uc.GetEmployees()` handler function.
And please do not add routes for other services.

2023-02-21 12:45 UTC, mrehanabbasi commented on models/employee.go
> +	Supervisor Supervisor `json:"supervisor" gorm:"foreignKey:ID;references:ID"`
The JSON for supervisor should also have `omitempty` since an employee may not have a supervisor.

2023-02-21 12:45 UTC, mrehanabbasi commented on models/employee.go
> +type Supervisor struct {
Coordinate with @MAsadJaved063 for `Supervisor` struct and @hamziHashmi for `Role` struct.

2023-03-01 07:21 UTC, mrehanabbasi requested changes

2023-03-01 07:21 UTC, mrehanabbasi commented on controller/empl_controller.go
> +	if err = db.Table("employees").Create(&employee).Error; err != nil {
Assign the default role of `Employee` to the employee if one is not provided in the request.

2023-03-01 07:21 UTC, mrehanabbasi commented on controller/empl_controller.go
> +			query = query.Where(key+" = ?", value)
Instead of getting the exact value, a better approach will be to get the item which contains that value.
E.g. for `http://localhost:8080/v1/employees?name=Sheraz`, it should return all the values where the employee name contains the work "Sheraz".

2023-03-01 07:21 UTC, mrehanabbasi commented on controller/empl_controller.go
> +	c.JSON(http.StatusOK, gin.H{"message": "Employee deleted successfully"})
Instead of sending a message for deletion using `c.JSON()`, just send the status code of 204 i.e. No Content.
```go
c.Status(http.StatusNoContent)
```

2023-03-01 09:52 UTC, Shery535 commented on controller/empl_controller.go
> +			query = query.Where(key+" = ?", value)
Aoa i have confusion in it that it is working and returning all the values where the employee name contains the work "Sheraz".

2023-03-01 13:55 UTC, mrehanabbasi requested changes

2023-03-01 13:55 UTC, mrehanabbasi commented on models/employee.go
> +	gorm.Model
Just add `Id` field. `gorm.Model` adds some other values as well like `Created At`, `UpdatedAt`, `DeletedAt` etc which aren't required at the time.

2023-03-01 13:55 UTC, mrehanabbasi commented on controller/empl_controller.go
> +		employee.Role = "Employee"
You need to check for three things here:
1. Get `RoleId` from DB.
2. Check if `Employee` role exists in the database.
3. If a role is provided in the request, check if it exists in the DB and throw an error if it doesn't exist there. If it exists, assign `RoleId` from the database.

2023-03-01 13:55 UTC, mrehanabbasi commented on controller/empl_controller.go
> +			query = query.Where(key+" = ?", value)
What I meant was that e.g. if there are multiple employees with names like "Sheraz Ahmad", "Muhammad Sheraz", "Sheraz Afridi" etc., sending `?name=Sheraz` query parameter should return all these employees.

2023-03-07 09:41 UTC, mrehanabbasi approved these changes

2023-03-07 10:42 UTC, merged